// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_LQ3PhsXXmLW6IQ8E-6Vz7C-Bi9I-Dao',
    appId: '1:906638254114:web:08fd2d99e8d5df718c2a7b',
    messagingSenderId: '906638254114',
    projectId: 'ecosync-bcc6a',
    authDomain: 'ecosync-bcc6a.firebaseapp.com',
    storageBucket: 'ecosync-bcc6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVWhrsu3RnBNBFbBSTKSmsyx86idqeOA8',
    appId: '1:906638254114:android:c0af6b5c5816b0f78c2a7b',
    messagingSenderId: '906638254114',
    projectId: 'ecosync-bcc6a',
    storageBucket: 'ecosync-bcc6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCjwK3GdCv9ErY0ascMAIy2_E25sUNGi4',
    appId: '1:906638254114:ios:0c2090cb278ef0098c2a7b',
    messagingSenderId: '906638254114',
    projectId: 'ecosync-bcc6a',
    storageBucket: 'ecosync-bcc6a.firebasestorage.app',
    iosClientId: '906638254114-nf9n5sl4n4k33g4pfogo85e4itd0ccdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCjwK3GdCv9ErY0ascMAIy2_E25sUNGi4',
    appId: '1:906638254114:ios:0c2090cb278ef0098c2a7b',
    messagingSenderId: '906638254114',
    projectId: 'ecosync-bcc6a',
    storageBucket: 'ecosync-bcc6a.firebasestorage.app',
    iosClientId: '906638254114-nf9n5sl4n4k33g4pfogo85e4itd0ccdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_LQ3PhsXXmLW6IQ8E-6Vz7C-Bi9I-Dao',
    appId: '1:906638254114:web:cafc4bc0bddfe5ab8c2a7b',
    messagingSenderId: '906638254114',
    projectId: 'ecosync-bcc6a',
    authDomain: 'ecosync-bcc6a.firebaseapp.com',
    storageBucket: 'ecosync-bcc6a.firebasestorage.app',
  );
}
